plugins:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/Exit:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'