plugins:
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/Exit:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
